apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-weather-app-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: my-weather-app
    template:
        metadata:
            labels:
                app: my-weather-app
        spec:
            containers:
            - name: my-weather-app
              image: deadmetal85/my-weather-app
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: my-weather-app-service
spec:
    type: NodePort
    selector:
        app: my-weather-app
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30001
          protocol: TCP